#lang racket
(require "utils.rkt")
(require "composition.rkt")
(require "functional-graphics.rkt")
(require "vector.rkt")

(r:define-style simple-style "black" 6 'solid "white" 'solid)

(composer example ((head 150 75) (collar 150 125) (pelvis 150 225) (left-arm 100 150) (right-arm 200 150) (left-leg 100 300) (right-leg 200 300))
          (let* ((body-height (round (vdist collar pelvis)))
                 (head-radius (round (/ body-height 2)))
                 (arm-length body-height)
                 (neck-height (round (/ body-height 5)))
                 (leg-length (+ body-height neck-height)))
            (fixed-distance head collar (+ head-radius neck-height))
            (fixed-distance left-arm collar arm-length)
            (fixed-distance right-arm collar arm-length)
            (fixed-distance left-leg pelvis leg-length)
            (fixed-distance right-leg pelvis leg-length)
            (simple-style (r:line collar pelvis)
                          (r:line collar head)
                          (r:line collar left-arm)
                          (r:line collar right-arm)
                          (r:line pelvis left-leg)
                          (r:line pelvis right-leg)
                          (r:circle head head-radius))))

(example 300 500)
