#lang racket
(require "utils.rkt")
(require "composition.rkt")
(require "functional-graphics.rkt")
(require "vector.rkt")

(r:define-style simple-style "black" 6 'solid "white" 'solid)

(composer example ((head 150 75) (collar 150 125) (pelvis 150 225) (left-hand 100 150) (left-elbow 125 125) (right-hand 200 150) (right-elbow 175 125) (left-leg 100 300) (right-leg 200 300))
          (let* ((body-height (round (vdist collar pelvis)))
                 (head-radius (round (/ body-height 2)))
                 (arm-length body-height)
                 (upper-arm-length (/ arm-length 2))
                 (lower-arm-length (/ arm-length 2))
                 (neck-height (round (/ body-height 5)))
                 (leg-length (+ body-height neck-height)))
            (fixed-distance head collar (+ head-radius neck-height))
            (fixed-distance left-elbow collar upper-arm-length)
            (fixed-distance right-elbow collar upper-arm-length)
            (fixed-distance left-hand left-elbow lower-arm-length)
            (fixed-distance right-hand right-elbow lower-arm-length)
            (fixed-distance left-leg pelvis leg-length)
            (fixed-distance right-leg pelvis leg-length)
            (simple-style (r:line collar pelvis)
                          (r:line collar head)
                          (r:line collar left-elbow)
                          (r:line left-elbow left-hand)
                          (r:line collar right-elbow)
                          (r:line right-elbow right-hand)
                          (r:line pelvis left-leg)
                          (r:line pelvis right-leg)
                          (r:circle head head-radius))))

(example 300 500)
