#lang typed/racket
(require "vector.rkt")
(require "geometry.rkt")
(require "functional-graphics.rkt")
(require "joints.rkt")
(require "skeleton.rkt")
(require "setting.rkt")
(require "pattern-base.rkt")

(provide new-box-figure)

(define jts (jointset-def-new 100.0))
(define skel (skeleton-def-new jts))
(define body-style (r:wrap-style "black" 6 (r:color 0 128 0)))
(define eye-style (r:wrap-style "black" 1 "black"))
(define nose-style (r:wrap-style "gray" 1 "gray"))
(define mouth-style (r:wrap-style "black" 2 "white"))
(define pat (pattern-def-new skel (r:wrap-style "black" 6 "white")))

(attach-setting! jts (setting-option-proto "line-face" #t))
(attach-setting! jts (setting-option-proto "left-up" #f))
(attach-setting! jts (setting-option-proto "right-up" #f))

(define neck (attach-joint! jts 0.0 -50.0))
(define head (attach-joint-rel! jts 0.0 -100.0 neck))
(define pelvis (dynamic-joint scale () () (head neck)
                              (v+ neck (vscale (v- neck head) scale))))
(define left-shoulder (dynamic-joint scale () () (head neck)
                                     (v+ neck (vscale (vrotate-origin-deg (v- head neck) 90.0)
                                                      (* scale 0.5)))))
(define right-shoulder (dynamic-joint scale () () (head neck)
                                      (v+ neck (vscale (vrotate-origin-deg (v- head neck) -90.0)
                                                       (* scale 0.5)))))
(define left-hip (dynamic-joint scale () () (neck pelvis)
                                (v+ pelvis (vscale (vrotate-origin-deg (v- neck pelvis) 90.0)
                                                   (* scale 0.5)))))
(define right-hip (dynamic-joint scale () () (neck pelvis)
                                 (v+ pelvis (vscale (vrotate-origin-deg (v- neck pelvis) -90.0)
                                                   (* scale 0.5)))))
(define left-hand (attach-joint-rel! jts 150.0 150.0 neck))
(define left-elbow (dynamic-joint scale (left-up) () (left-shoulder left-hand)
                                  (hypot-known-legs left-shoulder left-hand (* scale (if left-up -0.4 0.4)))))
(define right-hand (attach-joint-rel! jts -150.0 150.0 neck))
(define right-elbow (dynamic-joint scale (right-up) () (right-shoulder right-hand)
                                   (hypot-known-legs right-shoulder right-hand (* scale (if right-up 0.4 -0.4)))))
(define left-foot (attach-joint-rel! jts 50.0 300.0 neck))
(define right-foot (attach-joint-rel! jts -50.0 300.0 neck))

(define face (attach-joint-rel! jts 0.0 0.0 head))
(define orig-top-of-head (dynamic-joint scale () () (head)
                                   (v- head (vec 0.0 (scale* scale 0.7)))))
(define top-of-head (attach-joint-rel! jts 0.0 -1.0 orig-top-of-head))
(define right-of-head (dynamic-joint scale () () (head top-of-head)
                                   (vrotate-deg top-of-head head +90.0)))
(define left-of-head (dynamic-joint scale () () (head top-of-head)
                                   (vrotate-deg top-of-head head -90.0)))
#|(define nose (dynamic-joint scale () () (face head top-of-head)
                            (translate-along-sphere head top-of-head face (scale* scale 0.2))))|#
(define mouth (dynamic-joint scale () () (face head top-of-head)
                             (translate-along-sphere head top-of-head face (scale* scale 0.4))))
(define left-mouth (dynamic-joint scale () () (mouth head left-of-head)
                                  (translate-along-sphere head left-of-head mouth (scale* scale 0.2))))
(define right-mouth (dynamic-joint scale () () (mouth head right-of-head)
                                   (translate-along-sphere head right-of-head mouth (scale* scale 0.2))))
(define left-eye (dynamic-joint scale () () (face head left-of-head)
                                (translate-along-sphere head left-of-head face (scale* scale 0.2))))
(define right-eye (dynamic-joint scale () () (face head right-of-head)
                                 (translate-along-sphere head right-of-head face (scale* scale 0.2))))

(void (attach-fixed-bone! skel head neck 0.5)
      (attach-fixed-bone! skel top-of-head head 0.7)
      (attach-limited-bone! skel left-hand left-shoulder 0.8)
      (attach-limited-bone! skel right-hand right-shoulder 0.8)
      (attach-limited-bone! skel face head 0.6)
      (attach-fixed-bone! skel left-foot left-hip 0.8)
      (attach-fixed-bone! skel right-foot right-hip 0.8))

(attach-poly! pat (list left-shoulder left-hip right-hip right-shoulder) body-style)

(attach-circle! pat head 0.7)
(attach-circle! pat left-eye 0.07 eye-style)
(attach-circle! pat right-eye 0.07 eye-style)
#|(attach-circle! pat nose 0.03 nose-style)|#

(attach-renderer! pat (ren-conditional "line-face"
                                       (ren-line left-mouth right-mouth)
                                       (ren-circle mouth 0.1 mouth-style)))

(attach-line! pat (cons left-foot left-hip) body-style)
(attach-line! pat (cons right-foot right-hip) body-style)
(attach-line! pat (cons left-hand left-elbow) body-style)
(attach-line! pat (cons left-elbow left-shoulder) body-style)
(attach-line! pat (cons right-hand right-elbow) body-style)
(attach-line! pat (cons right-elbow right-shoulder) body-style)

(define new-box-figure (pattern-constructor (pattern-lock pat 'box-figure-basic)))
